### ISSUE TITLE
trouble trying out the library

### ISSUE THREAD

**Issue by tobowers** [prysmaticlabs/go-bls#33]
Hi,

I'm having trouble just "getting started" here... I've tried both the go and the bazel method from the homepage and they don't seem to be working.

Go:
```
go test .
panic: this library must be built by bazel, but was not
```

Bazel:
```
15:30 ~/code/go/src/github.com/prysmaticlabs/go-bls (master) $ bazel test //...
ERROR: /Users/tobowers/code/go/src/github.com/prysmaticlabs/go-bls/BUILD.bazel:9:1: in _cgo_codegen rule //:go_default_library%darwin_arm%cgo_codegen: 
Traceback (most recent call last):
	File "/Users/tobowers/code/go/src/github.com/prysmaticlabs/go-bls/BUILD.bazel", line 9
		_cgo_codegen(name = 'go_default_library%darwin_arm%cgo_codegen')
	File "/private/var/tmp/_bazel_tobowers/8f099f8165c5b3a5833d694a19ea181d/external/io_bazel_rules_go/go/private/rules/cgo.bzl", line 260, in _cgo_codegen_impl
		fail(("unknown library has neither cc...))
unknown library has neither cc nor objc providers: //:go-lib
ERROR: Analysis of target '//:go_default_library' failed; build aborted: Analysis of target '//:go_default_library%darwin_arm%cgo_codegen' failed; build aborted
INFO: Elapsed time: 0.466s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 6072 targets configured)
FAILED: Build did NOT complete successfully (5 packages loaded, 6072 targets configured)
15:30 ~/code/go/src/github.com/prysmaticlabs/go-bls (master) $ 
```

I'm on OSX and I'm trying to experiment how to use this as a library wtihin different package.

**Comment by prestonvanloon** [comment]
Hey @tobowers, this package is quite rotten at this point. If you're looking for a golang bls library, checkout https://github.com/phoreproject/bls. 

It doesn't have this weird cgo and complex build issues.
